# Generated by Django 6.0.2 on 2026-02-22 18:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(editable=False, help_text='Auto-generated PO number (PO-YYYYMMDD-XXXX)', max_length=50, unique=True)),
                ('customer_id', models.IntegerField(help_text='ID of customer (from Authinator)')),
                ('start_date', models.DateField(blank=True, help_text='Date PO was signed/agreed', null=True)),
                ('expiration_date', models.DateField(blank=True, help_text='Target fulfillment deadline', null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', help_text='PO status', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Notes about this PO')),
                ('google_doc_url', models.URLField(blank=True, help_text='Google Doc URL reference', null=True)),
                ('hubspot_url', models.URLField(blank=True, help_text='HubSpot URL/ID reference', null=True)),
                ('created_by_user_id', models.IntegerField(help_text='ID of user who created this PO (from Authinator)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When this PO was closed', null=True)),
                ('closed_by_user_id', models.IntegerField(blank=True, help_text='ID of user who closed this PO', null=True)),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity ordered', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Negotiated price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True, default='', help_text='Notes about this line item')),
                ('item', models.ForeignKey(help_text='Item being ordered', on_delete=django.db.models.deletion.PROTECT, to='items.item')),
                ('po', models.ForeignKey(help_text='Parent purchase order', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchase_orders.purchaseorder')),
            ],
            options={
                'verbose_name': 'PO Line Item',
                'verbose_name_plural': 'PO Line Items',
                'ordering': ['id'],
            },
        ),
    ]
