# Generated by Django 6.0.2 on 2026-02-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='closed_by_user_id',
            field=models.CharField(blank=True, help_text='ID of user who closed this PO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_by_user_id',
            field=models.CharField(help_text='ID of user who created this PO (from Authinator)', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='customer_id',
            field=models.CharField(help_text='ID of customer (from Authinator)', max_length=255),
        ),
    ]
