# Generated by Django 6.0.2 on 2026-02-26 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0002_alter_purchaseorder_closed_by_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='polineitem',
            name='waived_quantity',
            field=models.IntegerField(default=0, help_text='Quantity waived by admin (will not be fulfilled)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
