# Generated by Django 6.0.2 on 2026-02-22 18:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0002_alter_item_created_by_user_id'),
        ('purchase_orders', '0002_alter_purchaseorder_closed_by_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, help_text='Auto-generated order number (ORD-YYYYMMDD-XXXX)', max_length=50, unique=True)),
                ('customer_id', models.CharField(help_text='ID of customer (from Authinator)', max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', help_text='Order status', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Notes about this order')),
                ('created_by_user_id', models.CharField(help_text='ID of user who created this order (from Authinator)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When this order was closed', null=True)),
                ('closed_by_user_id', models.CharField(blank=True, help_text='ID of user who closed this order', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity ordered', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per unit (from PO or overridden)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True, default='', help_text='Notes about this line item')),
                ('override_reason', models.TextField(blank=True, help_text='Reason if price or quantity was overridden', null=True)),
                ('item', models.ForeignKey(help_text='Item being ordered', on_delete=django.db.models.deletion.PROTECT, to='items.item')),
                ('order', models.ForeignKey(help_text='Parent order', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='orders.order')),
                ('po_line_item', models.ForeignKey(blank=True, help_text='PO line item this order fulfills from (null for ad-hoc)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_orders.polineitem')),
            ],
            options={
                'verbose_name': 'Order Line Item',
                'verbose_name_plural': 'Order Line Items',
                'ordering': ['id'],
            },
        ),
    ]
