# Generated by Django 6.0.2 on 2026-02-26 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='waived_quantity',
            field=models.IntegerField(default=0, help_text='Quantity waived (not to be delivered)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
