# Generated by Django 6.0.2 on 2026-02-22 18:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0002_alter_item_created_by_user_id'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(editable=False, help_text='Auto-generated delivery number (DEL-YYYYMMDD-XXXX)', max_length=50, unique=True)),
                ('customer_id', models.CharField(help_text='ID of customer (from Authinator)', max_length=255)),
                ('ship_date', models.DateField(help_text='Date the items were shipped')),
                ('tracking_number', models.CharField(help_text='Carrier tracking number', max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', help_text='Delivery status', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Notes about this delivery')),
                ('created_by_user_id', models.CharField(help_text='ID of user who created this delivery (from Authinator)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When this delivery was closed', null=True)),
                ('closed_by_user_id', models.CharField(blank=True, help_text='ID of user who closed this delivery', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(help_text='Unique serial number for this physical item', max_length=255, unique=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per unit (from Order or overridden)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True, default='', help_text='Notes about this line item')),
                ('override_reason', models.TextField(blank=True, help_text='Reason if price was overridden', null=True)),
                ('delivery', models.ForeignKey(help_text='Parent delivery', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='deliveries.delivery')),
                ('item', models.ForeignKey(help_text='Item being delivered', on_delete=django.db.models.deletion.PROTECT, to='items.item')),
                ('order_line_item', models.ForeignKey(blank=True, help_text='Order line item this delivery fulfills', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderlineitem')),
            ],
            options={
                'verbose_name': 'Delivery Line Item',
                'verbose_name_plural': 'Delivery Line Items',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['serial_number'], name='deliveries__serial__83ef19_idx')],
            },
        ),
    ]
