# Generated by Django 6.0.2 on 2026-02-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['customer_id'], name='deliveries__custome_2e03f8_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status'], name='deliveries__status_bdfe1b_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['ship_date'], name='deliveries__ship_da_bfa61c_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['tracking_number'], name='deliveries__trackin_029985_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['-created_at'], name='deliveries__created_5bbcd2_idx'),
        ),
    ]
