# Generated by Django 6.0.2 on 2026-02-22 18:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Product name (e.g., 'Camera LR', 'Node 4.6')", max_length=255)),
                ('version', models.CharField(blank=True, default='', help_text="Product version (e.g., '1.0', '4.6 GA')", max_length=50)),
                ('description', models.TextField(blank=True, default='', help_text='Product description')),
                ('msrp', models.DecimalField(decimal_places=2, help_text="Manufacturer's Suggested Retail Price (list price)", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('min_price', models.DecimalField(decimal_places=2, help_text='Minimum price (reference only, not enforced)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_by_user_id', models.IntegerField(help_text='ID of user who created this item (from Authinator)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['name', 'version'],
            },
        ),
    ]
