# Generated by Django 6.0.2 on 2026-02-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_by_user_id',
            field=models.CharField(help_text='ID of user who created this item (from Authinator)', max_length=255),
        ),
    ]
