# Generated by Django 6.0.2 on 2026-02-22 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('PO', 'Purchase Order'), ('ORDER', 'Order'), ('DELIVERY', 'Delivery')], help_text='Type of entity this attachment belongs to', max_length=20)),
                ('object_id', models.IntegerField(help_text='ID of the PO/Order/Delivery')),
                ('file', models.FileField(help_text='Uploaded file', upload_to='attachments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'gif', 'bmp', 'xlsx', 'xls', 'csv', 'doc', 'docx', 'txt'])])),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by_user_id', models.CharField(help_text='ID of user who uploaded this file (from Authinator)', max_length=255)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_attach_content_8c2e5a_idx')],
            },
        ),
    ]
