# Generated by Django 6.0.2 on 2026-02-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('PO', 'Purchase Order'), ('ORDER', 'Order'), ('DELIVERY', 'Delivery')], help_text='Type of entity that was overridden', max_length=20)),
                ('entity_id', models.IntegerField(help_text='ID of the PO/Order/Delivery')),
                ('entity_number', models.CharField(help_text='PO/Order/Delivery number for easy reference', max_length=50)),
                ('override_type', models.CharField(choices=[('CLOSE', 'Force Close'), ('WAIVE', 'Waive Quantity'), ('PRICE', 'Price Override'), ('ALLOCATION', 'Allocation Override'), ('OTHER', 'Other')], help_text='Type of override performed', max_length=20)),
                ('reason', models.TextField(help_text='Reason provided by admin for the override')),
                ('user_id', models.CharField(help_text='ID of admin user who performed the override (from Authinator)', max_length=255)),
                ('user_email', models.EmailField(blank=True, default='', help_text='Email of admin user who performed the override', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context about the override')),
            ],
            options={
                'verbose_name': 'Admin Override',
                'verbose_name_plural': 'Admin Overrides',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='core_admino_entity__f1d6b1_idx'), models.Index(fields=['user_id'], name='core_admino_user_id_ef6ff2_idx'), models.Index(fields=['-created_at'], name='core_admino_created_4a68eb_idx')],
            },
        ),
    ]
